### ISSUE TITLE
Wild Scenery

### ISSUE THREAD

**Issue by vacip31** [Moebius14/AnubiSMod#1]
Can I use the Wild West background in my village after the v24.06.12 update? It was giving an error whenever I tried to open it. What does Attack Only mean? Was it set to work only on opponents? When will I be able to use it in my own village?

**Comment by Moebius14** [comment]
Nope. This scenery isn't supported as main scenery, but attack only.
________________________________
From: vacip31 ***@***.***>
Sent: Wednesday, June 12, 2024 11:11:12 PM
To: Moebius14/AnubiSMod ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Moebius14/AnubiSMod] Wild Scenery (Issue #1)


Can I use the Wild West background in my village after the v24.06.12 update? It was giving an error whenever I tried to open it. What does Attack Only mean? Was it set to work only on opponents? When will I be able to use it in my own village?

**Comment by Moebius14** [comment]
Attack only means versus an opponent, yes.
________________________________
From: vacip31 ***@***.***>
Sent: Wednesday, June 12, 2024 11:11:12 PM
To: Moebius14/AnubiSMod ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Moebius14/AnubiSMod] Wild Scenery (Issue #1)


Can I use the Wild West background in my village after the v24.06.12 update? It was giving an error whenever I tried to open it. What does Attack Only mean? Was it set to work only on opponents? When will I be able to use it in my own village?

**Comment by vacip31** [comment]
When can I roughly start using it as my own background? It's really frustrating to pay for it and not be able to use it :smiley:

**Comment by Moebius14** [comment]
No planned. All defaut sceneries + Egypt and Pumpkin Graveyard are supported.
I don't wanna pay for it and spend hours to code for it, sorry.
________________________________

**Comment by vacip31** [comment]
Let me know when you want to code. You don't need to pay; I can give you my village temporarily for coding. I didn't have a GitHub account before. How can you contact me?

**Comment by Moebius14** [comment]
I need screenshots.. The remaining is with special tools..
I could quickly take required screenshots using anydesk.
________________________________

**Comment by vacip31** [comment]
My AnyDesk workspace code: You can connect now 1 441 030 881 I am available.

**Comment by Moebius14** [comment]
I'm on discord
________________________________

**Comment by Moebius14** [comment]
I will connect in few minutes
________________________________

**Comment by vacip31** [comment]
okay...

**Comment by vacip31** [comment]
Is there a specific resolution you want me to open the game in?
