### ISSUE TITLE
opening error

### ISSUE THREAD

**Issue by danielbthiele** [Moebius14/AnubiSMod#3]
when I try to download it, the .exe appears but then disappears, if I try to run it, it appears that Windows Defender did not allow me to open it
![{2EA5C633-768B-422C-9B86-140FC5333C9A}](https://github.com/user-attachments/assets/5400c3de-54d1-4753-812a-bc00772a17be)

**Comment by Moebius14** [comment]
Then add it to exclusion in win Defender. Because it's a false positive..
