### ISSUE TITLE
variable used before declaration

### ISSUE THREAD

**Issue by EspaDo** [Moebius14/AnubiSMod#4]
eben though $bRemoved2 is defined in line 88, that point is not always reached. this means line 104 crashes
-> declare var beforehand or check if it is already declared before trying the check

https://github.com/Moebius14/AnubiSMod/blob/master/COCBot/functions/Image%20Search/CheckTombs.au3#L104

**Comment by Moebius14** [comment]
Fixed, TY.

**Comment by Moebius14** [comment]
Fixed. TY.

**Comment by Moebius14** [comment]
Fixed. TY.
